theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
shell = ["zsh", "-c"]

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.insert]
j = { j = "normal_mode" } # Maps `jk` to exit insert mode